export interface FrontControlCabinetState {
  emergencyStopPressed: boolean;
  startPressed: boolean;
  stopPressed: boolean;
  resetPressed: boolean;
}

export interface ControlCabinetStates {
  front: FrontControlCabinetState;
  rear: { emergencyStopPressed: boolean; phaseRelayFault: boolean; safetyRelayFault: boolean };
  airPreparation: { lowPressure: boolean };
}

/** HMI feedback only: TRUE means pressed; no command is generated by the 3D scene. */
export const DEFAULT_CONTROL_CABINETS: ControlCabinetStates = {
  front: { emergencyStopPressed: false, startPressed: false, stopPressed: false, resetPressed: false },
  rear: { emergencyStopPressed: false, phaseRelayFault: false, safetyRelayFault: false },
  airPreparation: { lowPressure: false },
};
