import type { CellLayout, CellState, MachineState, MagazineData, ProductType, SlotType } from './types';
import { CELL_LAYOUT_PRESET } from '../config/cellLayoutPreset';

const emptyMachine = (): MachineState => ({
  productType: 1,
  plcState: 4,
  enabled: true,
  alarm: false,
  disablePending: false,
  powerAllowed: true,
  resetAllowed: false,
  manualControlAllowed: false,
  manualDoorOpenAllowed: false,
  manualDoorCloseAllowed: false,
  manualHatchOpenAllowed: false,
  manualHatchCloseAllowed: false,
  manualChuckOpenAllowed: false,
  manualChuckCloseAllowed: false,
  doorOpen: false,
  doorClosed: true,
  hatchOpen: false,
  hatchClosed: true,
  chuckOpen: false,
  chuckClosed: true,
  partPresent: false,
  partReady: false,
  mode: 'enabled',
  currentStep: 'Ожидает загрузку',
  serviceRequired: true,
  canAcceptService: true,
  recommendedOperation: 'LOAD',
  actualOperation: 'NONE',
  partState: 'EMPTY',
  partType: 'UNKNOWN',
  cycleExpectedS: 60,
  cycleElapsedS: 0,
  cycleRemainingS: 60,
  measuredCycleS: 64.2,
  useHmiCycleTime: true,
  cycleOvertime: false,
  activeErrors: [],
  lastErrors: [],
});

const initialZone = (length: number, filled = false): SlotType[] =>
  Array.from({ length }, (_, index) => filled ? (index % 4 === 0 ? 'detail' : 'blank') : 'empty');

const initialZoneProductTypes = (length: number): ProductType[] =>
  Array.from({ length }, (_, index) => (index % 3) + 1 as ProductType);

const initialMagazine = (id: 1 | 2): MagazineData => ({
  slots: initialZone(120, id === 1),
  productTypes: initialZoneProductTypes(120),
  state: {
    enabled: false,
    disablePending: false,
    ready: false,
    busy: false,
    done: false,
    error: false,
    finished: false,
    canTake: true,
    canPut: true,
    canChange: true,
    canEnable: true,
    powerAllowed: true,
    enableSequenceAllowed: true,
    enableCheckRobotReady: true,
    enableCheckNoError: true,
    enableCheckRobotReleased: true,
    enableCheckContent: true,
    enableCheckGeometry: true,
    fillAllowed: true,
    clearAllowed: true,
    editAllowed: true,
    pitchEditAllowed: true,
    currentBlank: 1,
    currentFreeSlot: 1,
    selectedBlank: 0,
    selectedFreeSlot: 0,
    actualOperation: 'NONE',
    rows: 12,
    columns: 10,
    pitchX: 60,
    pitchY: 60,
    safeAbove: 0,
    safeInside: 1400,
    activeErrors: [],
    lastErrors: [],
  },
});

export const DEFAULT_LAYOUT: CellLayout = structuredClone(CELL_LAYOUT_PRESET);

export const DEFAULT_STATE: CellState = {
	robot: {
    currentPoint: 0,
    x: 6200,
    y: 675,
    z: 180,
    busy: false,
    done: false,
    error: false,
    powerAllowed: true,
    stopAllowed: true,
    resetAllowed: false,
    blankProductType: 1,
    detailProductType: 0,
    blankAvailable: true,
    detailAvailable: false,
    gripper1Open: false,
    gripper1Closed: true,
    gripper2Open: true,
    gripper2Closed: false,
    rotatedToBlank: true,
    rotatedToDetail: false,
  },
  machines: [
    { ...emptyMachine(), productType: 1 },
    {
      ...emptyMachine(),
      productType: 2,
      hatchOpen: false,
      hatchClosed: true,
      mode: 'processing',
      partPresent: true,
      partReady: false,
      partState: 'LOADED',
      partType: 'BLANK',
      currentStep: 'Обрабатывает деталь',
      serviceRequired: false,
      canAcceptService: false,
      recommendedOperation: 'UNLOAD',
      cycleExpectedS: 60,
      cycleElapsedS: 38,
      cycleRemainingS: 22,
    },
    {
      ...emptyMachine(),
      productType: 3,
      mode: 'change',
      partPresent: true,
      partReady: true,
      partState: 'LOADED',
      partType: 'DETAIL',
      currentStep: 'Готов к обслуживанию',
      recommendedOperation: 'CHANGE',
    },
  ],
  magazines: [initialMagazine(1), initialMagazine(2)],
};
