import type { CellLayout, CellState, MachineState, MagazineData, ProductType, SlotType } from './types';

const emptyMachine = (): MachineState => ({
  productType: 1,
  plcState: 4,
  enabled: true,
  alarm: false,
  disablePending: false,
  powerAllowed: true,
  resetAllowed: false,
  doorOpen: false,
  doorClosed: true,
  chuckOpen: false,
  chuckClosed: true,
  partPresent: false,
  partReady: false,
  mode: 'enabled',
  currentStep: 'Ожидает загрузку',
  serviceRequired: true,
  canAcceptService: true,
  recommendedOperation: 'LOAD',
  actualOperation: 'NONE',
  partState: 'EMPTY',
  partType: 'UNKNOWN',
  cycleExpectedS: 60,
  cycleElapsedS: 0,
  cycleRemainingS: 60,
  measuredCycleS: 64.2,
  useHmiCycleTime: true,
  cycleOvertime: false,
  activeErrors: [],
  lastErrors: [],
});

const initialZone = (length: number, filled = false): SlotType[] =>
  Array.from({ length }, (_, index) => filled ? (index % 4 === 0 ? 'detail' : 'blank') : 'empty');

const initialZoneProductTypes = (length: number): ProductType[] =>
  Array.from({ length }, (_, index) => (index % 3) + 1 as ProductType);

const initialMagazine = (id: 1 | 2): MagazineData => ({
  zones: [initialZone(120, id === 1), initialZone(120), initialZone(60)],
  zoneProductTypes: [initialZoneProductTypes(120), initialZoneProductTypes(120), initialZoneProductTypes(60)],
  state: {
    enabled: false,
    disablePending: false,
    ready: false,
    busy: false,
    done: false,
    error: false,
    finished: false,
    canTake: true,
    canPut: true,
    canChange: true,
    canEnable: true,
    powerAllowed: true,
    enableSequenceAllowed: true,
    fillAllowed: true,
    clearAllowed: true,
    currentBlank: 1,
    currentFreeSlot: 1,
    selectedBlank: 0,
    selectedFreeSlot: 0,
    actualOperation: 'NONE',
    rows: 12,
    columns: 10,
    pitchX: 60,
    pitchY: 60,
    safeAbove: 0,
    safeInside: 1400,
    powered: false,
    homed: false,
    positionValid: true,
    recoveryRequired: false,
    indexAllowed: false,
    zone1EditAllowed: true,
    indexing: false,
    indexDone: false,
    axisError: false,
    axisBusy: false,
    axisDone: false,
    axisPosition: 0,
    axisStep: 'Привод выключен',
    activeErrors: [],
    lastErrors: [],
  },
});

export const DEFAULT_LAYOUT: CellLayout = {
  coordinate: {
    origin: { x: 0, y: 0, z: 0 },
    direction: { x: 1, y: 1, z: 1 },
  },
  floor: { lengthX: 13200, widthY: 3900 },
  machine: {
    sizeX: 2806.7,
    sizeY: 1670,
    sizeZ: 1873.6,
    doorTravel: 1120,
    machines: [
      { position: { x: 0, y: 1450, z: 0 } },
      { position: { x: 4900, y: 1450, z: 0 } },
      { position: { x: 9800, y: 1450, z: 0 } },
    ],
  },
  portal: {
    position: { x: 300, y: 1050, z: 0 },
    lengthX: 12000,
    widthY: 1350,
    frameThicknessZ: 120,
    frameDepthY: 110,
    frameBottomZ: 2250,
    supportSize: 180,
    supportInsetX: 180,
  },
  robot: {
    yBeamHeight: 190,
    yBeamWidthX: 300,
    zBaseLength: 520,
    zColumnWidth: 120,
  },
  indexedConveyors: [{
    position: { x: 8500, y: 80, z: 0 },
    columnsX: 10,
    zoneRowsY: [12, 12, 6],
    pitchX: 60,
    pitchY: 60,
    slotDiameter: 42,
    slatWidthX: 650,
    slatThickness: 18,
    rollerRadius: 95.5,
    workingHeight: 820,
    lowerBeltWidthX: 580,
    lowerBeltHeight: 530,
    lowerBeltSpeed: 550,
    binWidthX: 800,
    binLengthY: 650,
    binHeight: 420,
  }, {
    position: { x: 10500, y: 80, z: 0 },
    columnsX: 10,
    zoneRowsY: [12, 12, 6],
    pitchX: 60,
    pitchY: 60,
    slotDiameter: 42,
    slatWidthX: 650,
    slatThickness: 18,
    rollerRadius: 95.5,
    workingHeight: 820,
    lowerBeltWidthX: 580,
    lowerBeltHeight: 530,
    lowerBeltSpeed: 550,
    binWidthX: 800,
    binLengthY: 650,
    binHeight: 420,
  }],
  animation: {
    motionResponse: 7,
    mechanismResponse: 6,
  },
};

export const DEFAULT_STATE: CellState = {
	robot: {
    x: 6200,
    y: 675,
    z: 180,
    busy: false,
    done: false,
    error: false,
    powerAllowed: true,
    stopAllowed: true,
    resetAllowed: false,
    blankProductType: 1,
    detailProductType: 0,
    blankAvailable: true,
    detailAvailable: false,
    gripper1Open: false,
    gripper1Closed: true,
    gripper2Open: true,
    gripper2Closed: false,
    rotatedToBlank: true,
    rotatedToDetail: false,
  },
  machines: [
    { ...emptyMachine(), productType: 1 },
    {
      ...emptyMachine(),
      productType: 2,
      doorOpen: false,
      doorClosed: true,
      mode: 'processing',
      partPresent: true,
      partReady: false,
      partState: 'LOADED',
      partType: 'BLANK',
      currentStep: 'Обрабатывает деталь',
      serviceRequired: false,
      canAcceptService: false,
      recommendedOperation: 'UNLOAD',
      cycleExpectedS: 60,
      cycleElapsedS: 38,
      cycleRemainingS: 22,
    },
    {
      ...emptyMachine(),
      productType: 3,
      mode: 'change',
      partPresent: true,
      partReady: true,
      partState: 'LOADED',
      partType: 'DETAIL',
      currentStep: 'Готов к обслуживанию',
      recommendedOperation: 'CHANGE',
    },
  ],
  magazines: [initialMagazine(1), initialMagazine(2)],
};
